// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFmXjS-WLis2BrBXqOm43J3MAB3vVumA',
    appId: '1:470527284822:web:7eefcecc7a9331c9a14df7',
    messagingSenderId: '470527284822',
    projectId: 'pustguesthouse',
    authDomain: 'pustguesthouse.firebaseapp.com',
    storageBucket: 'pustguesthouse.appspot.com',
    measurementId: 'G-24CLFECL7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbruSppudazcG1yo4d9t0eRX_e4qklJoo',
    appId: '1:470527284822:android:88ff3cecbd4b4e0da14df7',
    messagingSenderId: '470527284822',
    projectId: 'pustguesthouse',
    storageBucket: 'pustguesthouse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsQLbF44YzePLMMmp5cVFXRUPwu5wvVhU',
    appId: '1:470527284822:ios:fb0876321c799bc6a14df7',
    messagingSenderId: '470527284822',
    projectId: 'pustguesthouse',
    storageBucket: 'pustguesthouse.appspot.com',
    iosBundleId: 'com.example.guestHousePust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsQLbF44YzePLMMmp5cVFXRUPwu5wvVhU',
    appId: '1:470527284822:ios:22a45c42ba9e8ef7a14df7',
    messagingSenderId: '470527284822',
    projectId: 'pustguesthouse',
    storageBucket: 'pustguesthouse.appspot.com',
    iosBundleId: 'com.example.guestHousePust.RunnerTests',
  );
}
